### ISSUE TITLE
Fusing error

### ISSUE THREAD

**Issue by mrhelloyellow** [DexterLabZ/syrius-extension#1]
![fusing](https://user-images.githubusercontent.com/20839872/173810164-cc15bd8e-be6c-4b24-82ce-383125869c54.png)

**Comment by uluCthulhu** [comment]
Hi,

Can you please provide a more detailed description of the error?
What were the steps before getting this?

Did you just try to fuse some QSR? Keep in mind that if there was ProofOfWork necessary in order to complete the transaction you were supposed to wait until success toast notification appeared or the "Fusing..." label changed to "Fused !" 

What browser and version were you using?

Anyway, a good UX solution will be adding a more obvious, blocking, loading spinner untill the PoW is done.

**Comment by qortish** [comment]
Hi, 
Chrome
Version 103.0.5060.114 (Official Build) (64-bit)
Brave
[Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)

I go to fuse tab, type the amount and click on fuse plasma button then get a popup "Are you sure you want to fuse AMOUNT" then I click ok and get an error right away just saying "error"

**Comment by uluCthulhu** [comment]
Weird. I have the exact same version and never had a problem with that.

If you can still reproduce it can you please right click on the extension page and then inspect element. There should be a console.error() line printed there. Could you please expand it and send a print screen with that?

Also, Is staking, delegating or sending transactions working for you?

**Comment by uluCthulhu** [comment]
So there was a problem in the znn.ts package about fusing plasma. Now it's fixed and this problem shouldn't occur anymore.

**Comment by uluCthulhu** [comment]
So there was a problem in the znn.ts package about fusing plasma. Now it's fixed and this problem shouldn't occur anymore.
