### ISSUE TITLE
Default node is localhost

### ISSUE THREAD

**Issue by 0x3639** [DexterLabZ/syrius-extension#11]
Looks like the default node is localhost.  It's not always possible to run a node on the computer where the browser extension is installed.  Can we have a menu or dropdown where the user can add an external node?  

![image](https://user-images.githubusercontent.com/5406130/184433309-93904dcc-6488-47f2-903f-8d8d418987f8.png)

**Comment by zenon-info** [comment]
It appears as those the user has the option to change the node to a 3rd party.  However, in order to access this screen the user must fist have a running local node.  Is it possible to change this workflow?  

Either:
1) allow a user to login without a working node and give them the option to change it, or
2) allow a user to change the node before they login so they can login without a working local node.

![image](https://user-images.githubusercontent.com/109799533/184505029-7fad7fb5-a089-49d3-9dcb-adc439901933.png)
